#!/bin/sh
# enumerate-sim-keys.sh <version> [deb-path] [output-file]
# Extract the UniFi Network Application's simulation/demo configuration
# keys by string-grepping ace.jar from the release .deb. Acts as a drift
# tripwire (a release that renames or drops keys changes this file) and as
# de facto documentation of the sim-mode surface.
# Output goes to docs/sim-keys/<version>.txt unless overridden.
# Requires: curl, ar (binutils), tar with xz, unzip, strings (binutils).
set -eu

version=$1
deb=${2:-}
out=${3:-docs/sim-keys/${version}.txt}

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

if [ -z "$deb" ]; then
    deb="$work/unifi.deb"
    curl -fsSL -o "$deb" "https://dl.ui.com/unifi/${version}/unifi_sysvinit_all.deb"
fi

cd "$work"
# The keys have moved between jars across releases (10.x: lib/internal/
# core.jar) — scan every jar under lib/ so relocation can't blind us.
ar p "$deb" data.tar.xz | tar -xJ ./usr/lib/unifi/lib
find ./usr/lib/unifi/lib -name '*.jar' | grep -q . \
    || { echo "no jars found in deb" >&2; exit 1; }

keys=$(find ./usr/lib/unifi/lib -name '*.jar' -print0 \
    | xargs -0 -n1 unzip -p 2>/dev/null \
    | strings \
    | grep -ohE 'is_simulation|demo\.[a-z0-9_]+' \
    | sort -u)
[ -n "$keys" ] || { echo "no simulation keys found — extraction drift?" >&2; exit 1; }

cd - >/dev/null
mkdir -p "$(dirname "$out")"
{
    echo "# Simulation/demo configuration keys found in ace.jar"
    echo "# Product: UniFi Network Application"
    echo "# Verified on: ${version}"
    echo "# Generated by scripts/enumerate-sim-keys.sh — do not edit"
    echo "$keys"
} > "$out"
echo "wrote $out ($(printf '%s\n' "$keys" | wc -l | tr -d ' ') keys)"
